server:
  port: 9201
spring:
  application:
    name: es-demo
#  elasticsearch:
#    rest:
#      uris: http://localhost:9200
#      username: elasticsearch_brew
#      password: 4ZI0VnQkRS-OD20RJ_0a3Q
#      read-timeout: 3000
#      connection-timeout: 3000
